### ISSUE TITLE
Ranglista nem működik

### ISSUE THREAD

**Issue by fergaljon** [nyila7/Dusza2023-24#29]
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\CFY\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "c:\Users\CFY\OneDrive\Dokumentumok\GitHub\Dusza2023-24\mainGUI.py", line 139, in <lambda>
    command=lambda: controller.show_frame(
  File "c:\Users\CFY\OneDrive\Dokumentumok\GitHub\Dusza2023-24\mainGUI.py", line 79, in show_frame
    frame.populate_window()
  File "c:\Users\CFY\OneDrive\Dokumentumok\GitHub\Dusza2023-24\ranglistGUI.py", line 144, in populate_window
    a = get_lezar_ranglista()
  File "c:\Users\CFY\OneDrive\Dokumentumok\GitHub\Dusza2023-24\util.py", line 474, in get_lezar_ranglista
    jatekok[jatek][str(line[0])][str(line[1])][2] += float(line[4])
IndexError: list index out of range

**Comment by notyasuomain-cmd** [comment]
fixalatam
